name: Rick roll

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 24, 25-ea ]
    steps:
      - name: Récupération du code de la branche main
        uses: actions/checkout@v4

      - name: Initialisation de Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Compilation du code avec Maven
        run: mvn clean compile

      - name: Passer les tests unitaires
        run: mvn test

  on-failure:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: rick roll part
        uses: TejasvOnly/random-rickroll@v1.0
        with:
          percentage: 100
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
